### PR TITLE
package update

### PR DESCRIPTION
**Pull request by SychevIgor**
Microsoft.Azure.CosmosDB.Table updated to version 2.0 that is ga

### CODE REVIEW

**Comment by SychevIgor** [comment]
@georgewallace could you please look on it.

**Comment by georgewallace** [comment]
@SychevIgor Thanks for the contribution.  I don't work in the storage space anymore. @tamram Do you mind to review this update?

**Comment by SychevIgor** [comment]
@tamram ?

**Comment by SychevIgor** [comment]
@georgewallace any feedback?

**Comment by SychevIgor** [comment]
ok, microsoft don't care

**Pull request closed without merging**
